config/routes.rb
Rails.application.routes.draw do
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_form.rb
class ContactForm
  include ActiveModel::Model
  attr_reader :organization, :contact, :deal

  def initialize
    @organization = OrganizationFields.new
    @contact = ContactFields.new
    @deal = DealFields.new
  end

  def organization_attributes=(attributes)
    organization.assign_attributes(attributes)
  end

  def contact_attributes=(attributes)
    contact.assign_attributes(attributes)
  end

  def deal_attributes=(attributes)
    deal.assign_attributes(attributes)
  end

  def valid?
    [organization, contact, deal].map(&:valid?).all?
  end

  class OrganizationFields
    include ActiveModel::Model
    attr_accessor :name, :description
    validates :name, presence: true
  end

  class ContactFields
    include ActiveModel::Model
    attr_accessor :name, :email
    validates :name, presence: true
  end

  class DealFields
    include ActiveModel::Model
    attr_accessor :description
    validates :description, presence: true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @form = ContactForm.new

    @form.assign_attributes(
      organization_attributes: { name: "name1", description: "desc1" },
      contact_attributes: { name: "name2", email: "email" },
      deal_attributes: { description: "desc" }
    )
  end

  def create
    @form = ContactForm.new
    @form.assign_attributes(contact_form_params)
    @form.valid?
    render :new
  end


  private

  def contact_form_params
    params.require(:contact_form).permit(
      organization_attributes: [:name, :description],
      contact_attributes: [:name, :email],
      deal_attributes: [:description]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<h1>Contact form</h1>

<%= form_with(model: @form, url: contacts_path) do |f| %>
  <fieldset>
    <%= f.fields_for :organization do |organization_fields| %>
      <h2>Organization details</h2>

      <div>
      <%= organization_fields.label :name %>
      <%= organization_fields.text_field :name %>
      <%= organization_fields.object.errors.full_messages_for(:name) %>
      </div>

      <div>
      <%= organization_fields.label :description %>
      <%= organization_fields.text_field :description %>
      </div>
    <% end %>
  </fieldset>

  <fieldset>
    <%= f.fields_for :contact do |contact_fields| %>
      <h2>Contact details</h2>

      <div>
      <%= contact_fields.label :name %>
      <%= contact_fields.text_field :name %>
      <%= contact_fields.object.errors.full_messages_for(:name) %>
      </div>

      <div>
      <%= contact_fields.label :email %>
      <%= contact_fields.text_field :email %>
      </div>
    <% end %>
  </fieldset>

  <fieldset>
    <%= f.fields_for :deal do |deal_fields| %>
      <h2>Deal details</h2>

      <div>
      <%= deal_fields.label :description %>
      <%= deal_fields.text_field :description %>
      <%= deal_fields.object.errors.full_messages_for(:description) %>
      </div>
    <% end %>
  </fieldset>

  <%= f.button "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormObjectsExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>